# Generated by Django 4.2.9 on 2024-07-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('college', models.TextField()),
                ('place', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=50)),
                ('puc_result', models.IntegerField()),
                ('cet_rank', models.IntegerField()),
                ('category', models.CharField(max_length=4)),
                ('contact', models.IntegerField()),
                ('total_fee', models.IntegerField()),
                ('paid_fee', models.IntegerField()),
            ],
        ),
    ]
