# Generated by Django 4.2.9 on 2024-07-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('college', models.TextField()),
                ('place', models.CharField(max_length=100)),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('AIML', 'AIML'), ('Civil', 'Civil'), ('Mech', 'Mech')], max_length=50)),
                ('puc_result', models.IntegerField()),
                ('cet_rank', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(max_length=4)),
                ('contact', models.IntegerField()),
                ('total_fee', models.IntegerField()),
                ('paid_fee', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Studentdata',
        ),
    ]
