# Generated by Django 4.2.9 on 2024-07-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dynamic_fields',
            field=models.JSONField(default=dict),
        ),
    ]
