# Generated by Django 4.2.9 on 2024-07-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_student_dynamic_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dynamic_fields',
        ),
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='paid_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
