# Generated by Django 4.2.9 on 2024-07-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_student_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('AIML', 'AIML'), ('Civil', 'Civil'), ('Mech', 'Mech'), ('Mech/Civil', 'Mech/Civil'), ('Mech/AIML', 'Mech/AIML'), ('Mech/ECE', 'Mech/ECE'), ('Mech/CSE', 'Mech/CSE'), ('Civil/AIML', 'Civil/AIML'), ('Civil/ECE', 'Civil/ECE'), ('Civil/CSE', 'Civil/CSE'), ('AIML/ECE', 'AIML/ECE'), ('AIML/CSE', 'AIML/CSE'), ('ECE/CSE', 'ECE/CSE')], max_length=50)),
                ('puc_result', models.IntegerField()),
                ('cet_rank', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(max_length=4)),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
