# Generated by Django 4.2.9 on 2024-07-13 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
