# Generated by Django 4.2.9 on 2024-07-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_inquiry_date_alter_student_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
