# Generated by Django 4.2.9 on 2024-07-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_inquiry_date_alter_student_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='paid_fee',
            field=models.IntegerField(),
        ),
    ]
