# Generated by Django 4.2.9 on 2024-07-17 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_contact_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
